### ISSUE TITLE
White when hovering over the left side of the text

### ISSUE THREAD

**Issue by posh5** [BeardedBear/bearded-theme#104]
Not sure if this something forgotten, but whenever I hover over the left side no matter the theme it displays that block in a blinding white flash. Image link:

![image](https://user-images.githubusercontent.com/104591599/224924106-c72abfa8-e5cc-4430-8907-0f6fa898c50d.png)

**Comment by BeardedBear** [comment]
It's strange, I can't reproduce the bug on my side.

- Do you have an extension that would add this frame? 
- Does this behavior also occur with native themes, or other themes? 
- Does it happen with previous versions of the theme?
- I can't understand where this red band on the left side of the text could come from, it doesn't seem to be native to VSCode, could it come from an extension related to the language you use?

**Comment by posh5** [comment]
I do not have any other extensions other than Discord RPC, and "Driver" from WDK. This behavior does not occur with native themes or other themes and it is only the BeardedBear one that had this issue. Maybe the fact that I'm using Visual Studio instead of Visual Studio Code might be the issue.

The language is C++

Let me know what you think!

Thanks.

**Comment by BeardedBear** [comment]
Ok I get it, you are using Visual Studio, and my extension is only designed for VSCode, the themes that are available for Visual Studio were not designed by me, they are unofficial ports...

I've already received an issue because of that here : https://github.com/BeardedBear/bearded-theme/issues/103

there are 2 unofficial ports : 
- https://github.com/dnhuy4869/custom-theme-vs2022/issues/1
- https://github.com/daomtthuan/visual-studio-bearded-theme/issues/1

**Comment by posh5** [comment]
Ahh okay, sorry my bad. I hope you release a version for visual studio! Your projects are awesome.

Thanks.
