### ISSUE TITLE
In some cases, common variables showing up as red

### ISSUE THREAD

**Issue by sipolac** [BeardedBear/bearded-theme#110]
These are both Bearded Theme Arc, in files that have a `.py` extension. Not sure why one has common variables as red while the other doesn't. (I assume the non-red one is "correct"?) This is my favorite pack of themes so would love to see them to work consistently!

<img width="448" alt="Screenshot 2023-04-20 at 7 30 16 PM" src="https://user-images.githubusercontent.com/1937093/233507542-793f9c50-1f72-480c-b08b-957b5e063ded.png">
<img width="443" alt="Screenshot 2023-04-20 at 7 30 09 PM" src="https://user-images.githubusercontent.com/1937093/233507544-84a1f9dd-ec86-4899-977a-85871cf5fee3.png">

**Comment by sipolac** [comment]
I'm seeing now that there are other differences, like the coloring of `math.factorial`.

**Comment by BeardedBear** [comment]
hello! thanks for your feedback!

The normal color of variables on other languages is red (if it bothers you, there is a discussion where I explain how to change some elements of the theme here: https://github.com/BeardedBear/bearded-theme/discussions/75. 

However, I don't understand why there is this change between two identical files, on my side, the only way I could find to have the variables displayed in the correct way (so red) is to install an extension to add a better support of the Python syntax, since by default on VSCode, many elements are only available with the addition of scopes via Semantic Highlighting.

Do you have a specific extension for Python syntax?

**Comment by sipolac** [comment]
Thanks!

For the red code, my installed Python extensions are: Python and Pylance (both Microsoft). For the non-red code, I have Python and Pylint.

**Comment by BeardedBear** [comment]
sorry for the response time, but without the Pylance extension, it doesn't give me access to the syntax colorization scopes, Pylint is only there to indicate code errors, you need Pylance (or equivalent) to have the proper syntax colorization :(
