### ISSUE TITLE
[SCSS] Nested tags are colorless

### ISSUE THREAD

**Issue by hug33k** [BeardedBear/bearded-theme#116]
Nested tags when doing SCSS doesn't show properly.

I tried multiple combinations as you can see but only tags are affected by that issue.
<img width="302" alt="image" src="https://github.com/BeardedBear/bearded-theme/assets/1793678/5fc53685-637b-4880-b9fb-e712131c769e">

I also tested with more nesting but still the same:
<img width="302" alt="image" src="https://github.com/BeardedBear/bearded-theme/assets/1793678/ed827116-f592-42df-965f-fc6ea5bf847e">

Let me know if you need more details/informations

**Comment by BeardedBear** [comment]
Hey Hugo! Sorry but I can't do anything about this detail, it's a choice I had to make, because the Scope used by VSCode for SCSS tags is the same as for some properties like "cursor". If I hadn't made this choice, some properties wouldn't have the right color, as is regularly the case in many VSCode themes... 

![image](https://github.com/BeardedBear/bearded-theme/assets/7188702/5ce38ce2-a695-4953-95ce-bbfc6ee01d7f)
![image](https://github.com/BeardedBear/bearded-theme/assets/7188702/1ce8851a-5420-484a-877f-ab64d8e594f6)
![image](https://github.com/BeardedBear/bearded-theme/assets/7188702/4618645e-136b-4db4-b3cc-526f7df9c4cf)
