### ISSUE TITLE
Can you port to another IDE?

### ISSUE THREAD

**Issue by nahSystemu** [BeardedBear/bearded-theme#41]
I've been a VSCode user for some time now but recently I've switched to using JetBrains products, and was wondering if you could potentially port your theme to the JetBrains marketplace, would love to use your theme there

If you are interested:
[🔗 Creating Custom Themes for IntelliJ Platform IDEs](https://blog.jetbrains.com/platform/2019/03/creating-custom-themes-for-intellij-platform-ides/)

**Comment by geowarin** [comment]
I took a early stab at it.

https://github.com/geowarin/bearded-jb

It looks good enough for me with bearded-arc but more work is required to integrate other themes and fixing weird colors.
It will never be a perfect recreation but the main colors are here :)

Thank you @BeardedBear for the wonderful theme !

![image](https://user-images.githubusercontent.com/1045636/124913253-338d2d00-dfef-11eb-8524-1c7b6a69f876.png)

**Comment by BeardedBear** [comment]
Hey @geowarin !

I'm getting more and more requests for this, I've refactored the version 4 build system with this in mind, maybe we can see how to implement it, since you seem to be comfortable enough with it to make it a working theme :)

**Comment by geowarin** [comment]
I'd love to help. Feel free to ping me :)

**Comment by ujwaljain** [comment]
Any update on this? I'd also love to help.

**Comment by Den4ik-dev** [comment]
Is it possible to make such theme for ide visual studio c#?

**Comment by BeardedBear** [comment]
I've started to create a port for the Jetbrains IDE suite, but it's particularly painful and badly done. And since they are creating a brand new interface, I'm waiting to see if it will be easier to create one with that, in which case I would create a migration script from my JSON files generated from my VSCode themes.

As for Visual Studio, they have created an automatic porting tool, but it has a flaw that prevents me from using it, it doesn't handle transparency properly, and I use a lot of it to keep the generation of different versions consistent, so one day I'll try to try their tool again to see if they fixed this problem, for now I'm concentrating on VSCode which is the editor I use every day myself :)

**Comment by The-Plottwist** [comment]
Hey @BeardedBear, I recently switched from vscode to neovim and not thinking to switch back for various reasons.
However, the only extension I miss so much is your themes (I've  ditched every other).

Is there any chance to port for neovim. I'd love to help.
Have in mind that I have no experience in theme making but can help with neovim plugins, plugin writing and configuration.

**Comment by Thellior** [comment]
@The-Plottwist I was trying to do the same but I came across https://github.com/viniciusmuller/djanho. It's not 100% perfect but it's a beginning

**Comment by The-Plottwist** [comment]
I didn't know there was a tool for this. I will definitely try it out!
Thank you @Thellior.

**Comment by FelixKLG** [comment]
JetBrains has released Webstorm 2022.3 which includes the new UI to the general public.
<img width="672" alt="image" src="https://user-images.githubusercontent.com/44820580/204812365-4a230939-2c5d-475b-9e70-14673b80361b.png">

**Comment by leocampan** [comment]
Hello :) 
Is there any chance to have some kind of updates about this thread? I really can't wait to use Bearded themes on my JetBrains IDEs. 
Kindly

**Comment by VyrekXD** [comment]
I see it has the done label but where can i get the themes for IntelliJ Idea?
