### ISSUE TITLE
Syntax not colorized

### ISSUE THREAD

**Issue by rarodja** [BeardedBear/bearded-theme#70]
Issue one:
When you try to open and close lines of code in php, the last bracket is not colorized like first

![Issue 1](https://user-images.githubusercontent.com/74628132/153953787-46493c39-9d12-4be1-97df-b6acb12e4d83.png)

Issue two:
A simple style in HTML is not colorized in green like a class for example

![Issue2](https://user-images.githubusercontent.com/74628132/153954150-76a2379c-5d56-4dac-b239-d6278c1c8056.png)

Thank you very much for this wonderful theme.

**Comment by BeardedBear** [comment]
hello! for your first issue, it's impossible to fix it, VSCode considers it as a normal character, instead of understanding that it's a closing brace, I don't have the hand on it unfortunately : 
![image](https://user-images.githubusercontent.com/7188702/159269671-9e89ef15-a64f-4a6f-97f9-0b458db33495.png)

For the second, this will be fixed in the next release : 
![image](https://user-images.githubusercontent.com/7188702/159269770-c23aab46-4f8b-4e5f-817c-b869b0a0bebf.png)

but unfortunately I can't change the colors of CSS properties, VSCode thinks that everything is a property, without value: 
![image](https://user-images.githubusercontent.com/7188702/159270065-4dfd258b-1caa-464c-b744-a8216030fecf.png)

**Comment by connortwiegand** [comment]
This issue (the second one, namely pertaining to style="foo: bar;") is currently happening for me in v8.1.1. Am I missing something?

Love your theme extension btw!
