### ISSUE TITLE
6.0.0 light color theme too vivid

### ISSUE THREAD

**Issue by cllpse** [BeardedBear/bearded-theme#73]
Just switched to 6.0.0, and the light color theme – "Bearded Theme Light" – is WAY too vivid. The background changes to grey for some reason as well.

Latest version of VS Code. Running on macOS Monterey. No other theme extensions installed.

5.0.1:
<img width="872" alt="Screenshot 2022-03-22 at 11 28 06" src="https://user-images.githubusercontent.com/1655171/159462198-6fc9a698-9456-46b5-9faa-08215b015b52.png">

6.0.0:
<img width="877" alt="Screenshot 2022-03-22 at 11 28 27" src="https://user-images.githubusercontent.com/1655171/159462223-dfda8195-cfa2-4537-94db-ab66bc649ac0.png">

**Comment by BeardedBear** [comment]
I changed slightly the background of the Light theme so that we can differentiate the background of the menus or tooltips: 

![image](https://user-images.githubusercontent.com/7188702/159474912-85921b09-8d4b-4e16-afa8-c5d87d7e7cff.png)

But indeed the colors have become too vivid, I will make a correction to make them less vivid^^, thanks for the feedback ;)
